name: Back up Repositories

on:
# Turn schedule on once testing is complete    
#  schedule:
#    - cron: "0 0 * * *" # Runs at midnight every day of every month
  workflow_dispatch:

jobs:
  back-up:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        repo:
          - "https://github.com/IZGateway/izg-configuration-console"
          - "https://github.com/IZGateway/izg-transformation-ui"
#            - "https://github.com/IZGateway/izgw-hub"
#            - "https://github.com/IZGateway/izgw-core"
#            - "https://github.com/IZGateway/izgw-transform"
#            - "https://github.com/IZGateway/v2tofhir"
#            - "https://github.com/IZGateway/operations"
#            - "https://github.com/IZGateway/izgw-aws-lambda"
#            - "https://github.com/IZGateway/izgw-bom"
#            - "https://github.com/IZGateway/alpine-node-openssl-fips"
          - "https://github.com/IZGateway/iz-gateway-terraform"
#            - "https://github.com/IZGateway/izgw-performance-test"
#            - "https://github.com/IZGateway/ads-file-submission-app"
#            - "https://github.com/IZGateway/jmeter-setup-action"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install @larose/git-backup
        run: npm install -g @larose/git-backup

      - name: Back up ${{ matrix.repo }}
        run: |
          git-backup snapshot \
            --repo ${{ matrix.repo }} \
            --remote ${{ secrets.S3_REMOTE }}/${{ matrix.repo }} \
            --access-key-id ${{ secrets.AWS_ACCESS_KEY_ID }} \
            --secret-access-key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    
          git-backup prune \
            --repo ${{ matrix.repo }} \
            --remote ${{ secrets.S3_REMOTE }}/${{ matrix.repo }} \
            --access-key-id ${{ secrets.AWS_ACCESS_KEY_ID }} \
            --secret-access-key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            --retention-policy "monthly=3,weekly=4,daily=7"
