name: Back up Repositories

on:
# Turn schedule on once testing is complete    
#  schedule:
#    - cron: "0 0 * * *" # Runs at midnight every day of every month
  workflow_dispatch:

permissions:
  contents: read

jobs:
  back-up:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        repo:
          - izg-configuration-console
          - izg-transformation-ui
          - iz-gateway-terraform
#          - izgw-hub
#          - izgw-core
#          - izgw-transform
#          - v2tofhir
#          - operations
#          - izgw-aws-lambda
#          - izgw-bom
#          - alpine-node-openssl-fips
#          - izgw-performance-test
#          - ads-file-submission-app
#          - jmeter-setup-action

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          repository: IZGateway/${{ matrix.repo }}
          token: ${{secrets.IZGW_ALL_REPO_ACCESS_TOKEN}}
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{vars.AWS_REGION}}
                    
      - name: Back up ${{ matrix.repo }}
        run: |
            BACKUP_DIR="${{ github.workspace }}/backups"
            mkdir -p "$BACKUP_DIR"
            REPO_NAME="${{ matrix.repo }}"
            TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
            BACKUP_FILE="${BACKUP_DIR}/${REPO_NAME}_backup_${TIMESTAMP}.tar.gz"
            git archive --format=tar.gz HEAD > $BACKUP_FILE
            aws s3 cp $BACKUP_FILE s3://izgateway-github-backup/$REPO_NAME/            