name: Back up Repositories

on:
# Turn schedule on once testing is complete    
#  schedule:
#    - cron: "0 0 * * *" # Runs at midnight every day of every month
  workflow_dispatch:

permissions:
  contents: read

jobs:
  back-up:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        repo:
          - izg-configuration-console
          - izg-transformation-ui
#          - izgw-hub
#          - izgw-core
#          - izgw-transform
#          - v2tofhir
#          - operations
#          - izgw-aws-lambda
#          - izgw-bom
#          - alpine-node-openssl-fips
#          - iz-gateway-terraform
#          - izgw-performance-test
#          - ads-file-submission-app
#          - jmeter-setup-action

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install @larose/git-backup
        run: npm install -g @larose/git-backup

      - name: Back up ${{ matrix.repo }}
        run: |
          git-backup snapshot \
            --repo https://${{secrets.IZGW_ALL_REPO_ACCESS_TOKEN_AUSTIN}}@github.com/IZGateway/${{ matrix.repo }} \
            --remote ${{ secrets.S3_REMOTE }}/${{ matrix.repo }} \
            --access-key-id ${{ secrets.AWS_ACCESS_KEY_ID }} \
            --secret-access-key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    
          git-backup prune \
            --repo https://${{secrets.IZGW_ALL_REPO_ACCESS_TOKEN_AUSTIN}}@github.com/IZGateway/${{ matrix.repo }} \
            --remote ${{ secrets.S3_REMOTE }}/${{ matrix.repo }} \
            --access-key-id ${{ secrets.AWS_ACCESS_KEY_ID }} \
            --secret-access-key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            --retention-policy "monthly=3,weekly=4,daily=7"
